version: "3"
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysqluser
      MYSQL_DATABASE: local
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqluser
    ports:
      - 3306:3306

  redis:
    image: "redis:latest"
    ports:
      - 7001:6379

  prometheus:
    image: prom/prometheus
    ports:
      - 9222:9090
    logging:
      driver: none

  grafana:
    image: grafana/grafana:latest
    ports:
      - 9333:3000
    user: "472"
    logging:
      driver: none

  nexus:
    image: sonatype/nexus:oss
    ports:
      - 8081:8081
    logging:
      driver: none
