version: "3"
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysqluser
      MYSQL_DATABASE: local
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqluser
    ports:
      - "3306:3306"

  redis:
    image: "redis:latest"
    ports:
      - "7001:6379"

  nexus:
    image: sonatype/nexus:oss
    volumes:
      - "nexus-data:/sonatype-work"
    ports:
      - "8081:8081"

volumes:
  nexus-data: {}
