spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local
    username: mysqluser
    password: mysqluser
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 7001
