config:
  mysql:
    jdbc-url: jdbc:mysql://localhost:3306/local
    username: mysqluser
    password: mysqluser
    driver-class-name: com.mysql.cj.jdbc.Driver
    pool-name: master
    minimum-idle: 15
    maximum-pool-size: 15
    leak-detection-threshold: 0 # disabled
  redis:
    host: 127.0.0.1
    port: 7001
  elasticsearch:
    host: 127.0.0.1
    port: 9300
    cluster-name: docker-cluster
  cors:
    origin: http://localhost:8080
  oauth2-google:
    client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
    client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
    scope: openid,email

spring:
  security:
    user:
      name: securityuser
      password: securityuser

