server:
    port: 8080
    error:
        whitelabel.enabled: false
    servlet:
        session:
            cookie:
                max-age: 7d
spring:
    profiles.active: local
    resources:
        static-locations:
            - classpath:/static/
    mvc:
        static-path-pattern: /static/**
