version: "3"
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysqluser
      MYSQL_DATABASE: local
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqluser
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    ports:
      - 7001:6379

  elasticsearch:
    image: elasticsearch:7.4.0
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    expose:
      - 9300
